/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnboxProtocolRouteImport } from './routes/unbox-protocol'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as SupportRouteImport } from './routes/support'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as SellerOnboardingRouteImport } from './routes/seller-onboarding'
import { Route as SellerRouteImport } from './routes/seller'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PressRouteImport } from './routes/press'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as GuaranteeRouteImport } from './routes/guarantee'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as DisputesRouteImport } from './routes/disputes'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BecomeSellerRouteImport } from './routes/become-seller'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AffiliateRouteImport } from './routes/affiliate'
import { Route as AdvertiseRouteImport } from './routes/advertise'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SellerIndexRouteImport } from './routes/seller.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SellerTeamRouteImport } from './routes/seller.team'
import { Route as SellerRegisterRouteImport } from './routes/seller.register'
import { Route as SellerProductsRouteImport } from './routes/seller.products'
import { Route as SellerOrdersRouteImport } from './routes/seller.orders'
import { Route as SellerLoginRouteImport } from './routes/seller.login'
import { Route as SellerFinanceRouteImport } from './routes/seller.finance'
import { Route as SellerDashboardRouteImport } from './routes/seller.dashboard'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as AdminSellersRouteImport } from './routes/admin.sellers'
import { Route as AdminSellerRequestsRouteImport } from './routes/admin.seller-requests'
import { Route as AdminPayoutsRouteImport } from './routes/admin.payouts'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminFinanceRouteImport } from './routes/admin.finance'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminBankSettingsRouteImport } from './routes/admin.bank-settings'

const UnboxProtocolRoute = UnboxProtocolRouteImport.update({
  id: '/unbox-protocol',
  path: '/unbox-protocol',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerOnboardingRoute = SellerOnboardingRouteImport.update({
  id: '/seller-onboarding',
  path: '/seller-onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerRoute = SellerRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PressRoute = PressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const GuaranteeRoute = GuaranteeRouteImport.update({
  id: '/guarantee',
  path: '/guarantee',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const DisputesRoute = DisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeSellerRoute = BecomeSellerRouteImport.update({
  id: '/become-seller',
  path: '/become-seller',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateRoute = AffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertiseRoute = AdvertiseRouteImport.update({
  id: '/advertise',
  path: '/advertise',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerIndexRoute = SellerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SellerRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SellerTeamRoute = SellerTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => SellerRoute,
} as any)
const SellerRegisterRoute = SellerRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => SellerRoute,
} as any)
const SellerProductsRoute = SellerProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => SellerRoute,
} as any)
const SellerOrdersRoute = SellerOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => SellerRoute,
} as any)
const SellerLoginRoute = SellerLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => SellerRoute,
} as any)
const SellerFinanceRoute = SellerFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => SellerRoute,
} as any)
const SellerDashboardRoute = SellerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => SellerRoute,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSellersRoute = AdminSellersRouteImport.update({
  id: '/sellers',
  path: '/sellers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSellerRequestsRoute = AdminSellerRequestsRouteImport.update({
  id: '/seller-requests',
  path: '/seller-requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPayoutsRoute = AdminPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBankSettingsRoute = AdminBankSettingsRouteImport.update({
  id: '/bank-settings',
  path: '/bank-settings',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/advertise': typeof AdvertiseRoute
  '/affiliate': typeof AffiliateRoute
  '/auth': typeof AuthRoute
  '/become-seller': typeof BecomeSellerRoute
  '/careers': typeof CareersRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/disputes': typeof DisputesRoute
  '/feedback': typeof FeedbackRoute
  '/guarantee': typeof GuaranteeRoute
  '/orders': typeof OrdersRoute
  '/press': typeof PressRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/returns': typeof ReturnsRoute
  '/seller': typeof SellerRouteWithChildren
  '/seller-onboarding': typeof SellerOnboardingRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/support': typeof SupportRoute
  '/thank-you': typeof ThankYouRoute
  '/unbox-protocol': typeof UnboxProtocolRoute
  '/admin/bank-settings': typeof AdminBankSettingsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/seller-requests': typeof AdminSellerRequestsRoute
  '/admin/sellers': typeof AdminSellersRoute
  '/product/$id': typeof ProductIdRoute
  '/seller/dashboard': typeof SellerDashboardRoute
  '/seller/finance': typeof SellerFinanceRoute
  '/seller/login': typeof SellerLoginRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/products': typeof SellerProductsRoute
  '/seller/register': typeof SellerRegisterRoute
  '/seller/team': typeof SellerTeamRoute
  '/admin/': typeof AdminIndexRoute
  '/seller/': typeof SellerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advertise': typeof AdvertiseRoute
  '/affiliate': typeof AffiliateRoute
  '/auth': typeof AuthRoute
  '/become-seller': typeof BecomeSellerRoute
  '/careers': typeof CareersRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/disputes': typeof DisputesRoute
  '/feedback': typeof FeedbackRoute
  '/guarantee': typeof GuaranteeRoute
  '/orders': typeof OrdersRoute
  '/press': typeof PressRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/returns': typeof ReturnsRoute
  '/seller-onboarding': typeof SellerOnboardingRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/support': typeof SupportRoute
  '/thank-you': typeof ThankYouRoute
  '/unbox-protocol': typeof UnboxProtocolRoute
  '/admin/bank-settings': typeof AdminBankSettingsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/seller-requests': typeof AdminSellerRequestsRoute
  '/admin/sellers': typeof AdminSellersRoute
  '/product/$id': typeof ProductIdRoute
  '/seller/dashboard': typeof SellerDashboardRoute
  '/seller/finance': typeof SellerFinanceRoute
  '/seller/login': typeof SellerLoginRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/products': typeof SellerProductsRoute
  '/seller/register': typeof SellerRegisterRoute
  '/seller/team': typeof SellerTeamRoute
  '/admin': typeof AdminIndexRoute
  '/seller': typeof SellerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/advertise': typeof AdvertiseRoute
  '/affiliate': typeof AffiliateRoute
  '/auth': typeof AuthRoute
  '/become-seller': typeof BecomeSellerRoute
  '/careers': typeof CareersRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/disputes': typeof DisputesRoute
  '/feedback': typeof FeedbackRoute
  '/guarantee': typeof GuaranteeRoute
  '/orders': typeof OrdersRoute
  '/press': typeof PressRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/returns': typeof ReturnsRoute
  '/seller': typeof SellerRouteWithChildren
  '/seller-onboarding': typeof SellerOnboardingRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/support': typeof SupportRoute
  '/thank-you': typeof ThankYouRoute
  '/unbox-protocol': typeof UnboxProtocolRoute
  '/admin/bank-settings': typeof AdminBankSettingsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/seller-requests': typeof AdminSellerRequestsRoute
  '/admin/sellers': typeof AdminSellersRoute
  '/product/$id': typeof ProductIdRoute
  '/seller/dashboard': typeof SellerDashboardRoute
  '/seller/finance': typeof SellerFinanceRoute
  '/seller/login': typeof SellerLoginRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/products': typeof SellerProductsRoute
  '/seller/register': typeof SellerRegisterRoute
  '/seller/team': typeof SellerTeamRoute
  '/admin/': typeof AdminIndexRoute
  '/seller/': typeof SellerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/advertise'
    | '/affiliate'
    | '/auth'
    | '/become-seller'
    | '/careers'
    | '/cart'
    | '/checkout'
    | '/disputes'
    | '/feedback'
    | '/guarantee'
    | '/orders'
    | '/press'
    | '/profile'
    | '/reset-password'
    | '/returns'
    | '/seller'
    | '/seller-onboarding'
    | '/shipping'
    | '/shop'
    | '/support'
    | '/thank-you'
    | '/unbox-protocol'
    | '/admin/bank-settings'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/finance'
    | '/admin/orders'
    | '/admin/payouts'
    | '/admin/seller-requests'
    | '/admin/sellers'
    | '/product/$id'
    | '/seller/dashboard'
    | '/seller/finance'
    | '/seller/login'
    | '/seller/orders'
    | '/seller/products'
    | '/seller/register'
    | '/seller/team'
    | '/admin/'
    | '/seller/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/advertise'
    | '/affiliate'
    | '/auth'
    | '/become-seller'
    | '/careers'
    | '/cart'
    | '/checkout'
    | '/disputes'
    | '/feedback'
    | '/guarantee'
    | '/orders'
    | '/press'
    | '/profile'
    | '/reset-password'
    | '/returns'
    | '/seller-onboarding'
    | '/shipping'
    | '/shop'
    | '/support'
    | '/thank-you'
    | '/unbox-protocol'
    | '/admin/bank-settings'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/finance'
    | '/admin/orders'
    | '/admin/payouts'
    | '/admin/seller-requests'
    | '/admin/sellers'
    | '/product/$id'
    | '/seller/dashboard'
    | '/seller/finance'
    | '/seller/login'
    | '/seller/orders'
    | '/seller/products'
    | '/seller/register'
    | '/seller/team'
    | '/admin'
    | '/seller'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/advertise'
    | '/affiliate'
    | '/auth'
    | '/become-seller'
    | '/careers'
    | '/cart'
    | '/checkout'
    | '/disputes'
    | '/feedback'
    | '/guarantee'
    | '/orders'
    | '/press'
    | '/profile'
    | '/reset-password'
    | '/returns'
    | '/seller'
    | '/seller-onboarding'
    | '/shipping'
    | '/shop'
    | '/support'
    | '/thank-you'
    | '/unbox-protocol'
    | '/admin/bank-settings'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/finance'
    | '/admin/orders'
    | '/admin/payouts'
    | '/admin/seller-requests'
    | '/admin/sellers'
    | '/product/$id'
    | '/seller/dashboard'
    | '/seller/finance'
    | '/seller/login'
    | '/seller/orders'
    | '/seller/products'
    | '/seller/register'
    | '/seller/team'
    | '/admin/'
    | '/seller/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdvertiseRoute: typeof AdvertiseRoute
  AffiliateRoute: typeof AffiliateRoute
  AuthRoute: typeof AuthRoute
  BecomeSellerRoute: typeof BecomeSellerRoute
  CareersRoute: typeof CareersRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  DisputesRoute: typeof DisputesRoute
  FeedbackRoute: typeof FeedbackRoute
  GuaranteeRoute: typeof GuaranteeRoute
  OrdersRoute: typeof OrdersRoute
  PressRoute: typeof PressRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ReturnsRoute: typeof ReturnsRoute
  SellerRoute: typeof SellerRouteWithChildren
  SellerOnboardingRoute: typeof SellerOnboardingRoute
  ShippingRoute: typeof ShippingRoute
  ShopRoute: typeof ShopRoute
  SupportRoute: typeof SupportRoute
  ThankYouRoute: typeof ThankYouRoute
  UnboxProtocolRoute: typeof UnboxProtocolRoute
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unbox-protocol': {
      id: '/unbox-protocol'
      path: '/unbox-protocol'
      fullPath: '/unbox-protocol'
      preLoaderRoute: typeof UnboxProtocolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller-onboarding': {
      id: '/seller-onboarding'
      path: '/seller-onboarding'
      fullPath: '/seller-onboarding'
      preLoaderRoute: typeof SellerOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller': {
      id: '/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof SellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press': {
      id: '/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof PressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guarantee': {
      id: '/guarantee'
      path: '/guarantee'
      fullPath: '/guarantee'
      preLoaderRoute: typeof GuaranteeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disputes': {
      id: '/disputes'
      path: '/disputes'
      fullPath: '/disputes'
      preLoaderRoute: typeof DisputesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-seller': {
      id: '/become-seller'
      path: '/become-seller'
      fullPath: '/become-seller'
      preLoaderRoute: typeof BecomeSellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate': {
      id: '/affiliate'
      path: '/affiliate'
      fullPath: '/affiliate'
      preLoaderRoute: typeof AffiliateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertise': {
      id: '/advertise'
      path: '/advertise'
      fullPath: '/advertise'
      preLoaderRoute: typeof AdvertiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/': {
      id: '/seller/'
      path: '/'
      fullPath: '/seller/'
      preLoaderRoute: typeof SellerIndexRouteImport
      parentRoute: typeof SellerRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/seller/team': {
      id: '/seller/team'
      path: '/team'
      fullPath: '/seller/team'
      preLoaderRoute: typeof SellerTeamRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/register': {
      id: '/seller/register'
      path: '/register'
      fullPath: '/seller/register'
      preLoaderRoute: typeof SellerRegisterRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/products': {
      id: '/seller/products'
      path: '/products'
      fullPath: '/seller/products'
      preLoaderRoute: typeof SellerProductsRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/orders': {
      id: '/seller/orders'
      path: '/orders'
      fullPath: '/seller/orders'
      preLoaderRoute: typeof SellerOrdersRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/login': {
      id: '/seller/login'
      path: '/login'
      fullPath: '/seller/login'
      preLoaderRoute: typeof SellerLoginRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/finance': {
      id: '/seller/finance'
      path: '/finance'
      fullPath: '/seller/finance'
      preLoaderRoute: typeof SellerFinanceRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/dashboard': {
      id: '/seller/dashboard'
      path: '/dashboard'
      fullPath: '/seller/dashboard'
      preLoaderRoute: typeof SellerDashboardRouteImport
      parentRoute: typeof SellerRoute
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sellers': {
      id: '/admin/sellers'
      path: '/sellers'
      fullPath: '/admin/sellers'
      preLoaderRoute: typeof AdminSellersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seller-requests': {
      id: '/admin/seller-requests'
      path: '/seller-requests'
      fullPath: '/admin/seller-requests'
      preLoaderRoute: typeof AdminSellerRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payouts': {
      id: '/admin/payouts'
      path: '/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AdminPayoutsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bank-settings': {
      id: '/admin/bank-settings'
      path: '/bank-settings'
      fullPath: '/admin/bank-settings'
      preLoaderRoute: typeof AdminBankSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBankSettingsRoute: typeof AdminBankSettingsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPayoutsRoute: typeof AdminPayoutsRoute
  AdminSellerRequestsRoute: typeof AdminSellerRequestsRoute
  AdminSellersRoute: typeof AdminSellersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBankSettingsRoute: AdminBankSettingsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPayoutsRoute: AdminPayoutsRoute,
  AdminSellerRequestsRoute: AdminSellerRequestsRoute,
  AdminSellersRoute: AdminSellersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface SellerRouteChildren {
  SellerDashboardRoute: typeof SellerDashboardRoute
  SellerFinanceRoute: typeof SellerFinanceRoute
  SellerLoginRoute: typeof SellerLoginRoute
  SellerOrdersRoute: typeof SellerOrdersRoute
  SellerProductsRoute: typeof SellerProductsRoute
  SellerRegisterRoute: typeof SellerRegisterRoute
  SellerTeamRoute: typeof SellerTeamRoute
  SellerIndexRoute: typeof SellerIndexRoute
}

const SellerRouteChildren: SellerRouteChildren = {
  SellerDashboardRoute: SellerDashboardRoute,
  SellerFinanceRoute: SellerFinanceRoute,
  SellerLoginRoute: SellerLoginRoute,
  SellerOrdersRoute: SellerOrdersRoute,
  SellerProductsRoute: SellerProductsRoute,
  SellerRegisterRoute: SellerRegisterRoute,
  SellerTeamRoute: SellerTeamRoute,
  SellerIndexRoute: SellerIndexRoute,
}

const SellerRouteWithChildren =
  SellerRoute._addFileChildren(SellerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AdvertiseRoute: AdvertiseRoute,
  AffiliateRoute: AffiliateRoute,
  AuthRoute: AuthRoute,
  BecomeSellerRoute: BecomeSellerRoute,
  CareersRoute: CareersRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  DisputesRoute: DisputesRoute,
  FeedbackRoute: FeedbackRoute,
  GuaranteeRoute: GuaranteeRoute,
  OrdersRoute: OrdersRoute,
  PressRoute: PressRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ReturnsRoute: ReturnsRoute,
  SellerRoute: SellerRouteWithChildren,
  SellerOnboardingRoute: SellerOnboardingRoute,
  ShippingRoute: ShippingRoute,
  ShopRoute: ShopRoute,
  SupportRoute: SupportRoute,
  ThankYouRoute: ThankYouRoute,
  UnboxProtocolRoute: UnboxProtocolRoute,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
